import React from "react";
import teamlogo from "./myphoto.jpg";
import "./About.css"; 

const About = () => (
  <div className="about-container">
    <div className="about-content">
      <h1>Welcome to <span className="highlight">Invest with Intelligence</span></h1>
      <p className="tagline">
       <b> Empowering Business Decisions with Machine Learning </b>
      </p>

      <div className="intro-section">
        <h2>About Us</h2>
        <p>
          At <span className="highlight">Invest with Intelligence</span>, our mission is to revolutionize how entrepreneurs and investors make decisions about their business investments. We have embarked on a journey to build a web-based application that leverages the power of machine learning to predict the profit of startups and businesses.
        </p>
      </div>

      <div className="vision-section">
        <h2>Our Vision</h2>
        <p>
          We envision a future where entrepreneurs and investors can gain valuable insights into the potential profitability of their ventures with ease. By automating the process of profit prediction, we aim to provide a comprehensive solution that simplifies decision-making, enhances investment strategies, and ultimately contributes to the success of businesses.
        </p>
      </div>

      <div className="features-section">
        <h2>Key Features</h2>
        <ul className="feature-list">
          <li><strong>Predictive Analytics:</strong> Our application utilizes advanced machine learning models to predict the expected profit of a startup based on various features such as industry, funding, team size, location, and revenue.</li>
          <li><strong>End-to-End Solution:</strong> We offer a complete end-to-end solution that covers data preprocessing, feature engineering, model development, and deployment. Our goal is to provide a seamless experience for users, ensuring that every step of the process is accessible and user-friendly.</li>
          <li><strong>Usability:</strong> We prioritize usability, aiming to create an interface that is intuitive and easy to navigate. Whether you're an entrepreneur looking for insights or an investor seeking informed decisions, our platform is designed to cater to your needs.</li>
          <li><strong>Reliability:</strong> Our commitment to reliability ensures that users can trust the accuracy of the predictions generated by our machine learning models. We employ robust methodologies to enhance the reliability of our profit forecasts.</li>
        </ul>
      </div>

      <div className="how-it-works-section">
        <h2>How It Works</h2>
        <ol className="how-it-works-list">
          <li><strong>Input Data:</strong> Users provide startup features, including industry, funding, team size, location, and revenue.</li>
          <li><strong>Machine Learning Magic:</strong> Our machine learning models take these inputs, undergo data preprocessing and feature engineering, and generate predictions on the expected profit.</li>
          <li><strong>Decision Support:</strong> The predictions offer valuable insights, aiding entrepreneurs and investors in making informed decisions about their business endeavors.</li>
        </ol>
      </div>

      <div className="join-us-section">
        <h2>Join Us on this Journey</h2>
        <p>
          Whether you're an aspiring entrepreneur, an experienced investor, or someone passionate about the intersection of technology and business, <span className="highlight">Invest with Intelligencer</span> welcomes you. Stay tuned for updates as we work towards creating a platform that empowers you to navigate the complex world of startups and investments.
        </p>
      </div>

      <p className="footer">
        <strong>Empower your decisions with <span className="highlight">Invest with Intelligence</span> - Where Insights Drive Success!</strong>
      </p>

      <div className="team-members">
        <div className="team-member">
          <img src={teamlogo} alt="Team Member 1" className="team-member-img" />
          <h3>ABDUL WAHID</h3>
          <p>Frontend Developer</p>
        </div>
      
      </div>
    </div>
  </div>
);

export default About;
